"""empty message

Revision ID: 18a3a81da2a2
Revises: 96491cb21069
Create Date: 2023-11-21 19:51:45.428170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a3a81da2a2'
down_revision = '96491cb21069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_column('stripe_price')

    # ### end Alembic commands ###
