"""empty message

Revision ID: 50572a96fd11
Revises: c06626dde413
Create Date: 2023-10-28 08:58:08.536569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50572a96fd11'
down_revision = 'c06626dde413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_item_price', sa.Float(), nullable=True))

    with op.batch_alter_table('shoppingcarts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_total_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcarts', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('shipping_total_price')

    with op.batch_alter_table('shopping_cart_items', schema=None) as batch_op:
        batch_op.drop_column('shipping_item_price')

    # ### end Alembic commands ###
