"""empty message

Revision ID: 5c8dbfa1ea79
Revises: ecb179f2f0a8
Create Date: 2023-10-28 10:56:17.266219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c8dbfa1ea79'
down_revision = 'ecb179f2f0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('identification_type',
               existing_type=postgresql.ENUM('Dni', 'Nie', 'Passport', name='identification_type'),
               nullable=True)
        batch_op.alter_column('identification_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('identification_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('identification_type',
               existing_type=postgresql.ENUM('Dni', 'Nie', 'Passport', name='identification_type'),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
