"""empty message

Revision ID: ecb179f2f0a8
Revises: 50572a96fd11
Create Date: 2023-10-28 09:26:01.806385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ecb179f2f0a8'
down_revision = '50572a96fd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('products_detail', sa.String(length=300), nullable=False))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('shoppingcarts', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcarts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('products_detail')
        batch_op.drop_column('description')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
